steps:
# 1 Build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-north1-docker.pkg.dev/${PROJECT_ID}/frontend-vue', '.']
# 2 Push docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-north1-docker.pkg.dev/primal-stock-338302/frontend-vue']